Revamp the logic of the update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -15,42 +15,33 @@ remote_repo='https://github.com/adrfer/git-oh-my.git'
 name="$(git config user.name)"
 email="$(git config user.email)"
 
-# Backup local files, if any
+# Update existing files or download new ones
 if [[ -d "${local_repo}" ]]; then
-  echo -n "Backing up ${local_repo}..."
-  mv -f "${local_repo%/}"{," copy $(date +%s)"}
-  echo ' done.'
-fi
+  cd "${local_repo}"
+  echo -n "Updating some quick and dirty git files..."
 
-# Download remote files
-echo -n "Downloading some quick and dirty git files..."
-
-if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
-  echo ' done.'
+  if git checkout --quiet . >/dev/null 2>&1 && git pull --quiet origin master >/dev/null 2>&1; then
+    echo ' done.'
+    cd - >/dev/null 2>&1
+  else
+    echo 'Ooops, there was an error, try again.'
+    exit 1
+  fi
 else
-  echo 'Ooops, there was an error, try again.'
-  exit 1
+  echo -n "Downloading some quick and dirty git files..."
+
+  if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
+    echo ' done.'
+  else
+    echo 'Ooops, there was an error, try again.'
+    exit 1
+  fi
 fi
 
-# Update local files
-cd "${local_repo}"
-echo -n "Updating..."
-
-# Note: After installing or updating, the repository will become dirty since one will have configured the credentials
-if git checkout --quiet . >/dev/null 2>&1 && git pull --quiet origin master >/dev/null 2>&1; then
-  echo ' done.'
-  cd - >/dev/null 2>&1
-else
-  echo
-  echo 'Ooops, there was an error, try again.'
-  exit 1
-fi
-
-# Setup local files
+# Setup credentials
 ln -sf "${local_repo}/gitconfig" "${HOME}/.gitconfig"
 ln -sf "${local_repo}/gitignore" "${HOME}/.gitignore"
 
-# Setup credentials
 echo 'Now, setting up your credentials...'
 
 name_prompt='Your name: '
