Refactor check if git is available

diff --git a/update b/update
--- a/update
+++ b/update
@@ -8,7 +8,20 @@ set -u
 if ! command -v 'git' >/dev/null 2>&1; then
   echo -n 'Ooops, git not found. '
 
-  if [[ "$(uname)" = 'Darwin' ]]; then
+  if [[ "$(uname)" != 'Darwin' ]]; then
+    echo -e '\nGo to https://git-scm.com for more info.'
+    exit 1
+  fi
+
+  read -r -p 'Install it (y/n [n])? '
+
+  if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
+    echo 'Ok then, nothing much to see here.'
+    exit 0
+  fi
+
+  if ! command -v 'xcode-select' >/dev/null 2>&1; then
+    echo 'Ooops, Xcode not found. '
     read -r -p 'Install it (y/n [n])? '
 
     if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
@@ -16,23 +29,9 @@ if ! command -v 'git' >/dev/null 2>&1; then
       exit 0
     fi
 
-    if ! command -v 'xcode-select' >/dev/null 2>&1; then
-      echo 'Ooops, Xcode not found. '
-      read -r -p 'Install it (y/n [n])? '
-
-      if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
-        echo 'Ok then, nothing much to see here.'
-        exit 0
-      fi
-
-      if ! 'xcode-select' --install >/dev/null 2>&1; then
-        exit 1
-      fi
+    if ! 'xcode-select' --install >/dev/null 2>&1; then
+      exit 1
     fi
-
-  else
-    echo -e '\nGo to https://git-scm.com for more info.'
-    exit 1
   fi
 fi
 
