Update os check during update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -3,26 +3,12 @@
 set -e
 set -u
 
-# Fail fast if not on OS X
-
-if [[ "$(uname)" != 'Darwin' ]]; then
-  echo 'Ooops, this runs on OS X only.'
-  exit 1
-fi
-
 # Check if git is available
 
 if ! command -v 'git' >/dev/null 2>&1; then
   echo -n 'Ooops, git not found. '
-  read -r -p 'Install it (y/n [n])? '
 
-  if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
-    echo 'Ok then, nothing much to see here.'
-    exit 0
-  fi
-
-  if ! command -v 'xcode-select' >/dev/null 2>&1; then
-    echo 'Ooops, Xcode not found. '
+  if [[ "$(uname)" = 'Darwin' ]]; then
     read -r -p 'Install it (y/n [n])? '
 
     if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
@@ -30,9 +16,23 @@ if ! command -v 'git' >/dev/null 2>&1; then
       exit 0
     fi
 
-    if ! 'xcode-select' --install >/dev/null 2>&1; then
-      exit 1
+    if ! command -v 'xcode-select' >/dev/null 2>&1; then
+      echo 'Ooops, Xcode not found. '
+      read -r -p 'Install it (y/n [n])? '
+
+      if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
+        echo 'Ok then, nothing much to see here.'
+        exit 0
+      fi
+
+      if ! 'xcode-select' --install >/dev/null 2>&1; then
+        exit 1
+      fi
     fi
+
+  else
+    echo 'Go to https://git-scm.com for more info.'
+    exit 1
   fi
 fi
 
